name: Build Quicklinks + Redirects (fast)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "generate_quicklinks.py"
      - "_redirects"
      - "QUICKLINK_PINS.txt"
      - ".github/workflows/build-quicklinks.yml"
  schedule:
    - cron: "33 7 * * *"   # daily 07:33 UTC (staggered)
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: quicklinks-main
  cancel-in-progress: false

jobs:
  quicklinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python version
        run: python3 --version

      - name: Generate quicklinks + redirects
        env:
          QL_TOP_N: "8"
          QL_DAYS_WINDOW: "14"
          QL_DEBUG: "1"
        run: python3 generate_quicklinks.py

      - name: Commit changes (if any)
        env:
          BRANCH: ${{ github.ref_name }}
        shell: bash
        run: |
          set -e
          git config user.name "quicklinks-bot"
          git config user.email "quicklinks-bot@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # Only consider these files
          CHANGED="$(git status --porcelain -- AI_INDEX.md AI_QUICKLINKS.md _redirects)"
          if [ -n "$CHANGED" ]; then
            git add AI_INDEX.md AI_QUICKLINKS.md _redirects
            git commit -m "chore: auto-update quicklinks + redirects [skip ci]" || true
            git pull --rebase origin "$BRANCH" || true
            git push origin "HEAD:${BRANCH}" --force
          else
            echo "No changes to commit."
          fi
