name: Build All (Index + Quicklinks + Site + Brain)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "scripts/**"
      - "generate_quicklinks.py"
      - "generate_site_index.py"
      - "_headers"
      - ".github/workflows/build-all.yml"
  schedule:
    - cron: "27 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: build-all-main
  cancel-in-progress: false

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install pyyaml

      - name: Generate Quicklinks + Redirects
        env:
          QL_TOP_N: "8"
          QL_DAYS_WINDOW: "14"
          QL_DEBUG: "0"
        run: python3 generate_quicklinks.py

      - name: Generate Folder Indexes + Root
        run: python3 generate_site_index.py

      - name: Build Brain (export + index + search)
        run: |
          python3 scripts/export_brain.py
          python3 scripts/build_ai_index.py
          python3 scripts/build_search_page.py

      - name: Generate tiered indexes (core/systems/lore/rnd)
        run: python3 scripts/generate_tiered_indexes.py

      - name: Commit & Push (single commit)
        env:
          BRANCH: ${{ github.ref_name }}
        shell: bash
        run: |
          set -e
          git config user.name  "build-all-bot"
          git config user.email "build-all-bot@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # Always add the “known” files
          git add AI_INDEX.md AI_QUICKLINKS.md _redirects _headers **/index.html _brain/*.json _brain/*.gz search.html
          
          # Add the tiered index files only if any exist (prevents pathspec errors)
          TIER_FILES=$(ls *_TIER_*_INDEX.md 2>/dev/null || true)
          if [ -n "$TIER_FILES" ]; then
            git add $TIER_FILES
          fi
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: build all (site, quicklinks, brain export/index/search) [skip ci]" || true
          git pull --rebase origin "$BRANCH" || true
          git push origin "HEAD:$BRANCH" --force-with-lease || git push origin "HEAD:$BRANCH" --force
