name: Build Site Index (Netlify-friendly)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-site-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate folder index HTMLs
        run: python generate_site_index.py

      - name: Commit index files (if changed)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "site-index-bot"
          git config user.email "site-index-bot@users.noreply.github.com"
          if [[ -n "$(git status --porcelain | grep 'index.html' || true)" ]]; then
            git add **/index.html
            git commit -m "chore: auto-generate folder index pages [skip ci]" || echo "Nothing to commit"
            git push origin HEAD:${BRANCH}
          else
            echo "No index changes."
