name: Build All (AI Index + Quicklinks + Site Index + Tags + Change Feed + Cache)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "generate_ai_index.py"
      - "generate_quicklinks.py"
      - "generate_site_index.py"
      - "generate_tags_index.py"
      - "generate_change_feed.py"
      - "generate_cache_snapshot.py"
      - "QUICKLINK_PINS.txt"
      - "_headers"
      - ".github/workflows/build-all.yml"
  schedule:
    - cron: "27 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: build-all-main
  cancel-in-progress: false

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python 3
        run: python3 --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate AI_INDEX.md (if present)
        run: |
          if [ -f generate_ai_index.py ]; then python3 generate_ai_index.py; else echo "no generate_ai_index.py"; fi

      - name: Generate Quicklinks + Redirects
        env:
          QL_TOP_N: "8"
          QL_DAYS_WINDOW: "14"
          QL_DEBUG: "0"
        run: python3 generate_quicklinks.py

      - name: Generate Site Index (folder index.html files)
        run: python3 generate_site_index.py

      - name: Generate TAGS index
        run: python3 generate_tags_index.py

      - name: Generate CHANGE FEED
        env:
          CHANGE_DAYS: "14"
        run: python3 generate_change_feed.py

      - name: Generate Cache Snapshot
        env:
          CACHE_TOP_N: "20"
        run: python3 generate_cache_snapshot.py

      - name: Commit & Push (single commit)
        env:
          BRANCH: ${{ github.ref_name }}
        shell: bash
        run: |
          set -e
          git config user.name  "build-all-bot"
          git config user.email "build-all-bot@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # Stage known outputs first
          git add             AI_INDEX.md             AI_QUICKLINKS.md             CHANGE_FEED.md             TAGS_INDEX.md             tags/*.md             cache.html             _headers             _redirects             **/index.html 2>/dev/null || true

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: build all (index, quicklinks, tags, change feed, cache, site index) [skip ci]" || true
          git pull --rebase origin "${BRANCH}" || true
          git push origin "HEAD:${BRANCH}" --force-with-lease || git push origin "HEAD:${BRANCH}" --force
