name: Monitor Health

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch: # allow manual run

jobs:
  check-health:
    runs-on: ubuntu-latest
    steps:
      - name: Check health.json
        run: |
          set -e
          echo "Checking health.json..."
          
          # Download the file and capture HTTP status
          STATUS=$(curl -s -o /tmp/health.json -w "%{http_code}" https://psiopera-octopus-ogre-4372.netlify.app/health.json)

          if [ "$STATUS" != "200" ]; then
            echo "❌ Site returned status $STATUS"
            exit 1
          fi

          # Parse timestamp from JSON
          TIMESTAMP=$(jq -r '.timestamp' /tmp/health.json)
          NOW=$(date +%s)
          DIFF=$(( NOW - TIMESTAMP ))

          echo "now=$NOW ts=$TIMESTAMP age=${DIFF}s"

          # Fail if older than 15 minutes
          if [ "$DIFF" -gt 900 ]; then
            echo "❌ Timestamp is too old: ${DIFF} seconds"
            exit 1
          fi

          echo "✅ Health OK – Timestamp is ${DIFF} seconds old"
